# Generated by Django 6.0.4 on 2026-05-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertises',
            fields=[
                ('link', models.CharField()),
                ('name', models.CharField()),
                ('advertise_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
