# Generated by Django 6.0.4 on 2026-05-01 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertises',
            new_name='Advertise',
        ),
    ]
