# Generated by Django 6.0.4 on 2026-05-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_rename_advertises_advertise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('filter_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
