# Generated by Django 6.0.4 on 2026-05-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0003_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='filters',
            field=models.ManyToManyField(to='advertising.filter'),
        ),
    ]
