services:
  nginx:
    image: nginx:alpine
    ports:
      - 8000:80
    networks:
      - net
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static:/static
    restart: always

  backend:
    build: backend
    networks:
      - net
    volumes:
      - static:/static
      - database:/database
    env_file:
      - backend/.env
    restart: always

  bot:
    build: bot
    env_file:
      - bot/.env
    network_mode: host
    restart: always
    depends_on:
      - backend
  
networks:
  net:
    driver: bridge

volumes:
  static:
  database:
